<div id="header">
    <h2>FreeMarker Spring MVC Hello World</h2>
</div>
<div id="room_list_container">
    <#--<table>-->
        <#--<tr>-->
            <#--<td>nginx_version</td>-->
            <#--<td>${rtmp.nginx_version}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>nginx_rtmp_version</td>-->
            <#--<td>${rtmp.nginx_rtmp_version}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>compiler</td>-->
            <#--<td>${rtmp.compiler}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>built</td>-->
            <#--<td>${rtmp.built}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>pid</td>-->
            <#--<td>${rtmp.pid}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>uptime</td>-->
            <#--<td>${rtmp.uptime}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>naccepted</td>-->
            <#--<td>${rtmp.naccepted}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>bw_in</td>-->
            <#--<td>${rtmp.bw_in}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>bytes_in</td>-->
            <#--<td>${rtmp.bytes_in}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>bw_out</td>-->
            <#--<td>${rtmp.bw_out}</td>-->
        <#--</tr>-->
        <#--<tr>-->
            <#--<td>bytes_out</td>-->
            <#--<td>${rtmp.bytes_out}</td>-->
        <#--</tr>-->
        <#--<#list  rtmp.server.application as application>-->
        <#--<tr>-->
            <#--<td>-->
            <#--${application}-->
            <#--</td>-->
        <#--</tr>-->
    <#--</#list>-->
    <#--</table>-->
</div>
